version: '3'
services:
  ghost:
    image: ghost:1-alpine
    container_name: ghost-blog
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: 'P4sSw0rd0!'
      database__connection__database: ghost
    volumes:
      - ghost-volume:/var/lib/ghost
    ports:
      - 80:2368
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: ghost-db
    environment:
      MYSQL_ROOT_PASSWORD: 'P4sSw0rd0!'
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: always

volumes:
   ghost-volume:
   mysql-volume:
